### ISSUE TITLE
【仕様変更提案】tagsの内容をJSONの形ではなくyamlの形にしたい

### ISSUE THREAD

**Issue by TakuKobayashi** [antyuntyuntyun/qiita-cli#45]
現在、新しく記事を作成すると以下のような  `front-matter` が生成されます。

```yaml
---
id: 
title: 
tags: [{"name":"qiita-cli","versions":[]}]
---  
```

上部front-mattterの基本的な構造は `yaml` で記述されているのにその中にJSONが混じっているのは不自然だと思いますし、`yaml` と `JSON` でparseしないといけないのは不便に思います。
そのため `tags: []` の部分もyaml形式で記述するようにしてはいかがでしょうか?
